# Sử dụng giải mã phần cứng
hwdec=mediacodec
# Render bằng GPU
vo=gpu
gpu-context=android

# Tối ưu upscale/downscale
scale=ewa_lanczos
cscale=ewa_lanczos
dscale=mitchell

# Tối ưu hóa HDR
tone-mapping=hable
hdr-compute-peak=yes
target-peak=1000
tone-mapping-max-boost=1.5

# Giảm tải hệ thống
hwdec-codecs=all
video-sync=display-resample
cache-secs=20
deband=no
gpu-queue-count=2

# Hiển thị thông tin HDR
osd-on-seek=msg-bar
