# Sử dụng giải mã phần cứng
hwdec=mediacodec
# Render bằng GPU
vo=gpu
gpu-context=android

# Tối ưu upscale/downscale nhẹ hơn
scale=bilinear
cscale=bilinear
dscale=bilinear

# Tăng hiệu suất
interpolation=no
video-sync=display-resample
hwdec-codecs=all
cache-secs=15
deband=no
gpu-queue-count=2

# Giảm độ trễ, ưu tiên tải thấp
scale-antiring=0.5
dither-depth=8
